### ISSUE TITLE
feat: SOC integration issue list

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-ui#382]
**SX part**
- [ ] Add modal to change space profile #378 
- [ ] Add form to create a space #379 

**SOC part**

Depend on backend
- [ ] Deploy SOC contracts on Goerli with sample activity
- [ ] Create a Checkpoint or subgraph API following the format of SX API
- [ ] Add support on SX.js for SOC operations https://github.com/snapshot-labs/sx.js/issues/123
- [ ] Add support on Mana for SOC operations https://github.com/snapshot-labs/mana/issues/87

Frontend changes
- [ ] Add chain prefix in urls https://github.com/snapshot-labs/sx-ui/issues/381
- [ ] Support create space with SOC
- [ ] Add publish proposal with SOC
- [ ] Add cast vote with SOC
- [ ] Support execution with SOC
