### ISSUE TITLE
feat: add cover image

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-ui#580]
We should have a way to setup a cover image, it would look like this:
<img width="1469" alt="image" src="https://user-images.githubusercontent.com/16245250/234246596-6fc15064-e3d9-46a5-84d3-6b91b26cce23.png">

```[tasklist]
### Tasks
- [x] Increase allowed image size on pineapple
- [x] Add space-cover-sx type to stamp
- [x] Add avatar indexing on sx-subgraph
- [ ] Add cover to UI (display on profile, configuration on create and edit space form)
```
